# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
# stringData:
  mongo-root-username: dXNlcm5hbWU=      # required field for kubernetes.io/basic-auth
  mongo-root-password: cGFzc3dvcmQ= # required field for kubernetes.io/basic-auth
# immutable: true

